name: snakemake-globalDA-CompSign
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::snakemake-minimal =5.4.5
  - r-optparse
  #- conda-build=23.7.3
  - r-TMB
  - r-RcppEigen
  - r-ggplot2
  - r-compositions
  - r-MASS
  - r-MCMCpack
  - r-nnet
  - r-dendextend
  - r-Compositional
  - r-usedist

