name: snakemake-globalDA-cluster
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  # - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - appdirs=1.4.4
  - argcomplete=3.0.5
  - attrs=22.2.0
  - binutils_impl_linux-64=2.40
  - bioconductor-annotationdbi=1.60.0
  - bioconductor-biobase=2.58.0
  - bioconductor-biocfilecache=2.6.0
  - bioconductor-biocgenerics=0.44.0
  - bioconductor-biocio=1.8.0
  - bioconductor-biocparallel=1.32.5
  - bioconductor-biomart=2.54.0
  - bioconductor-biostrings=2.66.0
  - bioconductor-bsgenome=1.66.3
  - bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.3
  - bioconductor-data-packages=20231203
  - bioconductor-delayedarray=0.24.0
  - bioconductor-genomeinfodb=1.34.9
  - bioconductor-genomeinfodbdata=1.2.9
  - bioconductor-genomicalignments=1.34.0
  - bioconductor-genomicfeatures=1.50.2
  - bioconductor-genomicranges=1.50.0
  - bioconductor-hilda=1.12.0
  - bioconductor-iranges=2.32.0
  - bioconductor-keggrest=1.38.0
  - bioconductor-matrixgenerics=1.10.0
  - bioconductor-rhtslib=2.0.0
  - bioconductor-rsamtools=2.14.0
  - bioconductor-rtracklayer=1.58.0
  - bioconductor-s4vectors=0.36.0
  - bioconductor-summarizedexperiment=1.28.0
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene=3.2.2
  - bioconductor-xvector=0.38.0
  - bioconductor-zlibbioc=1.44.0
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.25.0
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - charset-normalizer=2.1.1
  - configargparse=1.7
  - cryptography=35.0.0
  - curl=7.87.0
  - datrie=0.8.2
  - docutils=0.17.1
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  # - gcc_impl_linux-64=13.2.0
  - gettext=0.21.1
  # - gfortran_impl_linux-64=13.2.0
  - gitdb=4.0.10
  - gitpython=3.1.18
  - graphite2=1.3.13
  - gsl=2.7
  # - gxx_impl_linux-64=13.2.0
  - harfbuzz=6.0.0
  - icu=70.1
  - idna=3.6
  - importlib-metadata=4.8.1
  - jags=4.3.2
  - jpeg=9e
  - jq=1.7.1
  - jsonschema=4.1.2
  - kernel-headers_linux-64=2.6.32
  # - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-devel_linux-64=13.2.0
  # - libgcc-ng=13.2.0
  # - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  # - libgomp=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.51.0
  # - libnsl=2.0.1
  - libopenblas=0.3.25
  - libpng=1.6.39
  # - libsanitizer=13.2.0
  - libsqlite=3.44.2
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=13.2.0
  # - libstdcxx-ng=13.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - make=4.3
  - ncurses=6.4
  - numpy=1.19.5
  - oniguruma=6.9.9
  - openssl=1.1.1w
  - pango=1.50.14
  - pcre2=10.40
  - pip=21.3.1
  - pixman=0.43.0
  - psutil=5.8.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.15
  - python_abi=3.6
  - pyyaml=5.4.1
  - r-abind=1.4_5
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-base=4.2.2
  - r-bh=1.84.0_0
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.4
  - r-boot=1.3_28.1
  - r-cachem=1.0.8
  - r-cli=3.6.2
  - r-coda=0.19_4
  - r-codetools=0.2_19
  - r-colorspace=2.1_0
  - r-cowplot=1.1.2
  - r-cpp11=0.4.7
  - r-crayon=1.5.2
  - r-curl=4.3.3
  - r-dbi=1.2.0
  - r-dbplyr=2.4.0
  - r-digest=0.6.34
  - r-dplyr=1.1.4
  - r-ellipsis=0.3.2
  - r-fansi=1.0.6
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-filelock=1.0.3
  - r-forcats=1.0.0
  - r-formatr=1.14
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-generics=0.1.3
  - r-getopt=1.20.4
  - r-ggplot2=3.4.4
  - r-glue=1.7.0
  - r-gtable=0.3.4
  - r-hms=1.1.3
  - r-httr=1.4.7
  - r-isoband=0.2.7
  - r-jsonlite=1.8.8
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-lattice=0.22_5
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-mass=7.3_60
  - r-matrix=1.6_4
  - r-matrixstats=1.2.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-munsell=0.5.0
  - r-mvtnorm=1.2_4
  - r-nlme=3.1_164
  - r-openssl=2.0.5
  - r-optparse=1.7.3
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-png=0.1_8
  - r-prettyunits=1.2.0
  - r-progress=1.2.3
  - r-purrr=1.0.2
  - r-r2jags=0.7_1
  - r-r2winbugs=2.1_22
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.12
  - r-rcppeigen=0.3.3.9.4
  - r-rcurl=1.98_1.10
  - r-restfulr=0.0.15
  - r-rjags=4_15
  - r-rjson=0.2.21
  - r-rlang=1.1.3
  - r-rsqlite=2.3.4
  - r-scales=1.3.0
  - r-snow=0.4_4
  - r-stringi=1.7.12
  - r-stringr=1.5.1
  - r-sys=3.4.2
  - r-tibble=3.2.1
  - r-tidyr=1.3.0
  - r-tidyselect=1.2.0
  - r-tmb=1.9.10
  - r-utf8=1.2.4
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-withr=2.5.2
  - r-xml=3.99_0.14
  - r-xml2=1.3.3
  - r-yaml=2.3.8
  - ratelimiter=1.2.0
  - readline=8.2
  - requests=2.28.1
  - sed=4.8
  - setuptools=58.0.4
  - six=1.16.0
  - smmap=3.0.5
  - snakemake-minimal=5.4.5
  - sqlite=3.44.2
  - sysroot_linux-64=2.12
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - typing_extensions=4.1.1
  - urllib3=1.26.15
  - wheel=0.37.1
  - wrapt=1.13.1
  - xmltodict=0.13.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yq=3.1.1
  - zipp=3.6.0
  - zlib=1.2.13
  - zstd=1.5.5