name: snakemake-globalDA
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::snakemake-minimal =5.4.5
  - python =3.6
  - numpy
  - conda-forge::r-TMB
  - r-ggplot2
  - r-optparse
  - r-mvtnorm
  - conda-forge::r-uuid


